Repository JeanBizeul/GrayTracer, pull requests merged in 2025-05, with the labels that each got.

#1 Add project coding style to the main branch
  .clang-format
  .github/workflows/RayRayRayRay.yml
  .gitignore
  Makefile
  Readme.md
  doc/Architectural decisions.md
  doc/Configuration file.md
  doc/How to read.md
  doc/Modules.md
  doc/Modules/Lights.md
  doc/Modules/Materials.md
  doc/Modules/Primitives.md
  doc/Modules/Renderers.md
  include/main.hpp
Labels: documentation, enhancement

#3 Fix CI rule
  .github/workflows/RayRayRayRay.yml
Labels: enhancement

#4 ✨ Add Math vec & point
  include/Math/Point.hpp
  include/Math/Point.tpp
  include/Math/Vec.hpp
  include/Math/Vec.tpp
Labels: enhancement

#8 🚚 ♻️ Use new math library in the already present core classes
  include/RayTracer/Camera.hpp
  include/RayTracer/Face.hpp
  include/RayTracer/I3dObject.hpp
  include/RayTracer/ILight.hpp
  include/RayTracer/IPrimitive.hpp
  include/RayTracer/IRenderer.hpp
  include/RayTracer/Ray.hpp
  include/RayTracer/Screen.hpp
  include/RayTracer/Segment.hpp
  src/Camera.hpp
  src/Face.hpp
  src/I3dObject.hpp
  src/IPrimitive.hpp
  src/Line.hpp
  src/Point.hpp
  src/Ray.hpp
  src/Screen.hpp
  src/Vector.hpp
Labels: Refactor

#14 Fix documentation mishaps and typos
  doc/Architectural decisions.md
  doc/How to read.md
  doc/Modules.md
  doc/Modules/Lights.md
  doc/Modules/Materials.md
  doc/Modules/Primitives.md
  doc/Modules/Renderers.md
Labels: documentation

#15 13 create config file documentation
  doc/Configuration file.md
Labels: documentation

#17 🐛 Fixed incorrect declaration of arrays
  doc/Configuration file.md
Labels: documentation

#18 ✨ Add Factory base class and sphere factory
  .gitignore
  Makefile
  include/Math/Point.hpp
  include/Math/Point.tpp
  include/Math/Vec.hpp
  include/Math/Vec.tpp
  include/RayTracer/AFace.hpp
  include/RayTracer/APrimitive.hpp
  include/RayTracer/APrimitive.tpp
  include/RayTracer/Camera.hpp
  include/RayTracer/DLLoader.hpp
  include/RayTracer/Face.hpp
  include/RayTracer/I3dObject.hpp
  include/RayTracer/IFace.hpp
  include/RayTracer/IFactory.hpp
  include/RayTracer/ILight.hpp
  include/RayTracer/IPrimitive.hpp
  include/RayTracer/IRenderer.hpp
  include/RayTracer/Ray.hpp
  include/RayTracer/Screen.hpp
  include/RayTracer/Segment.hpp
  src/lib/Factories/Primitives/Square/Makefile
  src/lib/Factories/Primitives/Square/src/Sphere.hpp
  src/lib/Factories/Primitives/Square/src/Sphere.tpp
  src/lib/Factories/Primitives/Square/src/SphereFactory.cpp
  src/lib/Factories/Primitives/Square/src/SphereFactory.hpp
Labels: enhancement

#22 ♻️ Remove Math::Point class
  include/Math/Point.hpp
  include/Math/Point.tpp
  include/Math/Point2.hpp
  include/Math/Point3.hpp
  include/Math/Point4.hpp
  include/Math/Vec.hpp
  include/Math/Vec.tpp
  include/Math/Vec2.hpp
  include/Math/Vec3.hpp
  include/Math/Vec4.hpp
  include/RayTracer/APrimitive.hpp
  include/RayTracer/APrimitive.tpp
  include/RayTracer/Camera.hpp
  include/RayTracer/I3dObject.hpp
  include/RayTracer/Ray.hpp
  include/RayTracer/Segment.hpp
  src/lib/Factories/Primitives/Square/src/Sphere.hpp
  src/lib/Factories/Primitives/Square/src/Sphere.tpp
  src/lib/Factories/Primitives/Square/src/SphereFactory.cpp
Labels: enhancement, Refactor

#23 Face update
  include/Math/Vec.hpp
  include/Math/Vec.tpp
  include/RayTracer/AFace.hpp
  include/RayTracer/APrimitive.hpp
  include/RayTracer/APrimitive.tpp
  include/RayTracer/DLLoader.hpp
  include/RayTracer/Face.hpp
  include/RayTracer/Face.tpp
  include/RayTracer/IFace.hpp
  include/RayTracer/IFactory.hpp
  include/RayTracer/Screen.hpp
  src/lib/Factories/Primitives/Square/src/SphereFactory.cpp
Labels: Refactor

#27 🔨 Make root makefiles propagate it's commands
  Makefile
  src/Plugins/Factories/Primitives/Sphere/Makefile
  src/Plugins/Factories/Primitives/Sphere/src/Sphere.hpp
  src/Plugins/Factories/Primitives/Sphere/src/Sphere.tpp
  src/Plugins/Factories/Primitives/Sphere/src/SphereFactory.cpp
  src/Plugins/Factories/Primitives/Sphere/src/SphereFactory.hpp
Labels: enhancement, Refactor

#29 ♻️ Changed hit handling for primitives
  include/Math/Vec.hpp
  include/Math/Vec.tpp
  include/RayTracer/APrimitive.hpp
  include/RayTracer/APrimitive.tpp
  include/RayTracer/Face.hpp
  include/RayTracer/Face.tpp
  include/RayTracer/IFactory.hpp
  include/RayTracer/Impact.hpp
  src/APrimitive.cpp
  src/Face.cpp
  src/Plugins/Factories/Primitives/Sphere/src/Sphere.hpp
  src/Plugins/Factories/Primitives/Sphere/src/Sphere.tpp
Labels: Refactor

#28 ♻️ Remove throw in favor of error logs in the destructor of the DLLoader
  include/RayTracer/DLLoader.hpp
Labels: bug, Refactor

#32 Add validation of scene configuration file
  .clang-format
  .github/workflows/RayRayRayRay.yml
  Makefile
  include/Math/Vec.tpp
  include/RayTracer/Camera.hpp
  include/RayTracer/DLLoader.hpp
  include/RayTracer/IFactory.hpp
  include/RayTracer/ILight.hpp
  include/RayTracer/Impact.hpp
  include/RayTracer/Ray.hpp
  include/RayTracer/Scene.hpp
  include/RayTracer/Screen.hpp
  include/RayTracer/Segment.hpp
  src/APrimitive.cpp
  src/Face.cpp
  src/Plugins/Factories/Primitives/Sphere/src/Sphere.hpp
  src/Plugins/Factories/Primitives/Sphere/src/Sphere.tpp
  src/Plugins/Factories/Primitives/Sphere/src/SphereFactory.cpp
  src/main.cpp
  src/parsing/SceneParser.cpp
  src/parsing/SceneParser.hpp
  tests/test.cfg
  tests/test.mtl
Labels: enhancement

#31 ✨ Add material factory
  .github/workflows/RayRayRayRay.yml
  Makefile
  doc/Modules/Materials.md
  include/Math/Vec.tpp
  include/RayTracer/APrimitive.hpp
  include/RayTracer/FactoryContext.hpp
  include/RayTracer/FactoryContext.tpp
  include/RayTracer/IFactory.hpp
  include/RayTracer/Material.hpp
  src/APrimitive.cpp
  src/Face.cpp
  src/main.cpp
  src/main.hpp
  src/plugins/Factories/Material/Makefile
  src/plugins/Factories/Material/src/MaterialFactory.cpp
  src/plugins/Factories/Material/src/MaterialFactory.hpp
  src/plugins/Factories/Primitives/Sphere/Makefile
  src/plugins/Factories/Primitives/Sphere/src/Sphere.hpp
  src/plugins/Factories/Primitives/Sphere/src/Sphere.tpp
  src/plugins/Factories/Primitives/Sphere/src/SphereFactory.cpp
  src/plugins/Factories/Primitives/Sphere/src/SphereFactory.hpp
Labels: documentation, enhancement
